resources:
  # - crds/pods.yaml
  - certificates-apiresourceschema.yaml
  - cert-manager-apiexport.yaml
  - cert-manager-cluster-role.yaml
  - cert-manager-cluster-role-binding.yaml
  - cert-manager-apibinding.yaml
