
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

// DNSRecordClusterListerExpansion allows custom methods to be added to DNSRecordClusterLister.
type DNSRecordClusterListerExpansion interface {}

// DNSRecordListerExpansion allows custom methods to be added to DNSRecordLister.
type DNSRecordListerExpansion interface {}
// DNSRecordNamespaceListerExpansion allows custom methods to be added to DNSRecordNamespaceLister.
type DNSRecordNamespaceListerExpansion interface {}
