
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

// DomainVerificationClusterListerExpansion allows custom methods to be added to DomainVerificationClusterLister.
type DomainVerificationClusterListerExpansion interface {}

// DomainVerificationListerExpansion allows custom methods to be added to DomainVerificationLister.
type DomainVerificationListerExpansion interface {}
