apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-glbc-controller-manager
rules:
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports
    verbs:
      - get
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports/content
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
