
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v3"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kuadrantv1 "github.com/kuadrant/kcp-glbc/pkg/apis/kuadrant/v1"

	"k8s.io/apimachinery/pkg/watch"

	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/types"

	kuadrantv1client "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned/typed/kuadrant/v1"
)

var domainVerificationsResource = schema.GroupVersionResource{Group: "kuadrant.dev", Version: "v1", Resource: "domainverifications"}
var domainVerificationsKind = schema.GroupVersionKind{Group: "kuadrant.dev", Version: "v1", Kind: "DomainVerification"}

type domainVerificationsClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *domainVerificationsClusterClient) Cluster(clusterPath logicalcluster.Path) kuadrantv1client.DomainVerificationInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &domainVerificationsClient{Fake: c.Fake, ClusterPath: clusterPath}
}


// List takes label and field selectors, and returns the list of DomainVerifications that match those selectors across all clusters.
func (c *domainVerificationsClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*kuadrantv1.DomainVerificationList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(domainVerificationsResource, domainVerificationsKind, logicalcluster.Wildcard, opts), &kuadrantv1.DomainVerificationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kuadrantv1.DomainVerificationList{ListMeta: obj.(*kuadrantv1.DomainVerificationList).ListMeta}
	for _, item := range obj.(*kuadrantv1.DomainVerificationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested DomainVerifications across all clusters.
func (c *domainVerificationsClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(domainVerificationsResource, logicalcluster.Wildcard, opts))
}
type domainVerificationsClient struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
	
}


func (c *domainVerificationsClient) Create(ctx context.Context, domainVerification *kuadrantv1.DomainVerification, opts metav1.CreateOptions) (*kuadrantv1.DomainVerification, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootCreateAction(domainVerificationsResource, c.ClusterPath, domainVerification), &kuadrantv1.DomainVerification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DomainVerification), err
}

func (c *domainVerificationsClient) Update(ctx context.Context, domainVerification *kuadrantv1.DomainVerification, opts metav1.UpdateOptions) (*kuadrantv1.DomainVerification, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateAction(domainVerificationsResource, c.ClusterPath, domainVerification), &kuadrantv1.DomainVerification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DomainVerification), err
}

func (c *domainVerificationsClient) UpdateStatus(ctx context.Context, domainVerification *kuadrantv1.DomainVerification, opts metav1.UpdateOptions) (*kuadrantv1.DomainVerification, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateSubresourceAction(domainVerificationsResource, c.ClusterPath, "status", domainVerification), &kuadrantv1.DomainVerification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DomainVerification), err
}

func (c *domainVerificationsClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewRootDeleteActionWithOptions(domainVerificationsResource, c.ClusterPath, name, opts), &kuadrantv1.DomainVerification{})
	return err
}

func (c *domainVerificationsClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewRootDeleteCollectionAction(domainVerificationsResource, c.ClusterPath, listOpts)

	_, err := c.Fake.Invokes(action, &kuadrantv1.DomainVerificationList{})
	return err
}

func (c *domainVerificationsClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*kuadrantv1.DomainVerification, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootGetAction(domainVerificationsResource, c.ClusterPath, name), &kuadrantv1.DomainVerification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DomainVerification), err
}

// List takes label and field selectors, and returns the list of DomainVerifications that match those selectors.
func (c *domainVerificationsClient) List(ctx context.Context, opts metav1.ListOptions) (*kuadrantv1.DomainVerificationList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(domainVerificationsResource, domainVerificationsKind, c.ClusterPath, opts), &kuadrantv1.DomainVerificationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kuadrantv1.DomainVerificationList{ListMeta: obj.(*kuadrantv1.DomainVerificationList).ListMeta}
	for _, item := range obj.(*kuadrantv1.DomainVerificationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *domainVerificationsClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(domainVerificationsResource, c.ClusterPath, opts))
}

func (c *domainVerificationsClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*kuadrantv1.DomainVerification, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootPatchSubresourceAction(domainVerificationsResource, c.ClusterPath, name, pt, data, subresources...), &kuadrantv1.DomainVerification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DomainVerification), err
}
