
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	kuadrantv1 "github.com/kuadrant/kcp-glbc/pkg/apis/kuadrant/v1"
	kuadrantv1listers "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/listers/kuadrant/v1"
	clientset "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned/cluster"
	scopedclientset "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned"
	"github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/informers/externalversions/internalinterfaces"
)

// DNSRecordClusterInformer provides access to a shared informer and lister for
// DNSRecords.
type DNSRecordClusterInformer interface {
	Cluster(logicalcluster.Name) DNSRecordInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kuadrantv1listers.DNSRecordClusterLister
}

type dNSRecordClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDNSRecordClusterInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSRecordClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredDNSRecordClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDNSRecordClusterInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSRecordClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords().Watch(context.TODO(), options)
			},
		},
		&kuadrantv1.DNSRecord{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSRecordClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredDNSRecordClusterInformer(client, resyncPeriod, cache.Indexers{
			kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
			kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,}, 
		f.tweakListOptions,
	)
}

func (f *dNSRecordClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&kuadrantv1.DNSRecord{}, f.defaultInformer)
}

func (f *dNSRecordClusterInformer) Lister() kuadrantv1listers.DNSRecordClusterLister {
	return kuadrantv1listers.NewDNSRecordClusterLister(f.Informer().GetIndexer())
}


// DNSRecordInformer provides access to a shared informer and lister for
// DNSRecords.
type DNSRecordInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kuadrantv1listers.DNSRecordLister
}
func (f *dNSRecordClusterInformer) Cluster(clusterName logicalcluster.Name) DNSRecordInformer {
	return &dNSRecordInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type dNSRecordInformer struct {
	informer cache.SharedIndexInformer
	lister kuadrantv1listers.DNSRecordLister
}

func (f *dNSRecordInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *dNSRecordInformer) Lister() kuadrantv1listers.DNSRecordLister {
	return f.lister
}

type dNSRecordScopedInformer struct {
	factory internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace string}

func (f *dNSRecordScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kuadrantv1.DNSRecord{}, f.defaultInformer)
}

func (f *dNSRecordScopedInformer) Lister() kuadrantv1listers.DNSRecordLister {
	return kuadrantv1listers.NewDNSRecordLister(f.Informer().GetIndexer())
}

// NewDNSRecordInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSRecordInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string,indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDNSRecordInformer(client, resyncPeriod,  namespace,indexers, nil)
}

// NewFilteredDNSRecordInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSRecordInformer(client scopedclientset.Interface, resyncPeriod time.Duration,  namespace string,indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords(namespace).Watch(context.TODO(), options)
			},
		},
		&kuadrantv1.DNSRecord{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSRecordScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDNSRecordInformer(client, resyncPeriod, f.namespace,cache.Indexers{ 
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}

