
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/informers/externalversions/internalinterfaces"
)

type ClusterInterface interface {
// DomainVerifications returns a DomainVerificationClusterInformer
	DomainVerifications() DomainVerificationClusterInformer
// DNSRecords returns a DNSRecordClusterInformer
	DNSRecords() DNSRecordClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new ClusterInterface.
func New(f internalinterfaces.SharedInformerFactory, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// DomainVerifications returns a DomainVerificationClusterInformer
func (v *version) DomainVerifications() DomainVerificationClusterInformer {
	return &domainVerificationClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
// DNSRecords returns a DNSRecordClusterInformer
func (v *version) DNSRecords() DNSRecordClusterInformer {
	return &dNSRecordClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
type Interface interface {
// DomainVerifications returns a DomainVerificationInformer
	DomainVerifications() DomainVerificationInformer
// DNSRecords returns a DNSRecordInformer
	DNSRecords() DNSRecordInformer
}

type scopedVersion struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace string
}

// New returns a new ClusterInterface.
func NewScoped(f internalinterfaces.SharedScopedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &scopedVersion{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DomainVerifications returns a DomainVerificationInformer
func (v *scopedVersion) DomainVerifications() DomainVerificationInformer {
	return &domainVerificationScopedInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
// DNSRecords returns a DNSRecordInformer
func (v *scopedVersion) DNSRecords() DNSRecordInformer {
	return &dNSRecordScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

