apiVersion: scheduling.kcp.io/v1alpha1
kind: Placement
metadata:
  name: default
spec:
  locationResource:
    group: workload.kcp.io
    resource: synctargets
    version: v1alpha1
  locationSelectors:
    - {}
  locationWorkspace: root:kuadrant
  namespaceSelector: {}
