
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package internalinterfaces

import (
	time "time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/cache"
	

	clientset "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned/cluster"
	scopedclientset "github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned"
	
)

// NewInformerFunc takes clientset.ClusterInterface and time.Duration to return a ScopeableSharedIndexInformer.
type NewInformerFunc func(clientset.ClusterInterface, time.Duration) kcpcache.ScopeableSharedIndexInformer

// SharedInformerFactory a small interface to allow for adding an informer without an import cycle
type SharedInformerFactory interface {
	Start(stopCh <-chan struct{})
	InformerFor(obj runtime.Object, newFunc NewInformerFunc) kcpcache.ScopeableSharedIndexInformer
}

// NewScopedInformerFunc takes scopedclientset.Interface and time.Duration to return a SharedIndexInformer.
type NewScopedInformerFunc func(scopedclientset.Interface, time.Duration) cache.SharedIndexInformer

// SharedScopedInformerFactory a small interface to allow for adding an informer without an import cycle
type SharedScopedInformerFactory interface {
	Start(stopCh <-chan struct{})
	InformerFor(obj runtime.Object, newFunc NewScopedInformerFunc) cache.SharedIndexInformer
}


// TweakListOptionsFunc is a function that transforms a metav1.ListOptions.
type TweakListOptionsFunc func(*metav1.ListOptions)
